### ISSUE TITLE
labels in registration form and confirmation mail not translated

### ISSUE THREAD

**Issue by peerlight** [oliverklee/ext-seminars#527]
labels in registration form and confirmation mail to attandee are not translated (to german)

- no label overrides by plugin.tx_seminars_pi1._LOCAL_LANG.de active
- Translations of Extensions in TYPO3 are up to date
- label for ###FEUSER_DATA### in RegistrationEditor.html Step1 is translated correctly
- rest of RegistrationEditor.html including prev/next not translated
- salutation in confirmation mail to attandee not translated

using
    TYPO3 9.5.14
    PHP 7.2.x
    seminars 3.0.0 - 3.0.1
    rn_base 1.11.1 - 1.11.2
    mkforms 9.5.2

how to debug this?

**Comment by peerlight** [comment]
Do you mean `typo3conf/l10n/de/seminars` or `typo3temp/var/cache/data/l10n`?

But both were cleared several times after upgrading seminars from 2.2.x to 3.x

**Comment by oliverklee** [comment]
Yes, those.
Could you also please test whether re-downloading the translations helps?

**Comment by peerlight** [comment]
No, this does not helped. I checked the labels in `typo3conf/l10n/de/seminars` and in `/Resources/Private/Language/` of the repo - all is there

Feature toggle newTranslationServer is off

What I noticed:
- error message in registration step 1 is translated
- in step 1 `###LABEL_SELECT_PRICE###` gets `<label>Price:</label>` but should be "Preis:"
- in step 2 `###LABEL_REGISTER_ENTERED_DATA###` is not translated but content of `###REGISTRATION_DATA###` gets translated, including labels of price and method_of_payment

**Comment by oliverklee** [comment]
That's strange.

What does your TypoScript in `config.` look like? Something like this (assuming that the site's first language is German)?

```
config {
    language = de
    sys_language_uid = 0
    locale_all = de_DE
    htmlTag_langKey = de_DE
}
```

**Comment by peerlight** [comment]
site configuration has 
```
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    direction: ltr
    flag: de
    languageId: '0'
```

but TS `config.language = de` was missing ... somehow gone during upgrade

Thank you, solved, can be closed
